AllCops:
  Exclude:
    - "**/*.erb"

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 225

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10
